### ISSUE TITLE
Add PHP block comment support

### ISSUE THREAD

**Issue by mcactive** [dgmid/TODOLists-WebScript-Sidebar#2]
Hi!

First I want to thank you for this tool, it's a very handy tool and I use it on a daily basis.

I was wondering if it's possible to add PHP block comment support. I use this a lot to explain the todo items. In my case it looks like this:

```
<?php
/*
* TODO: this item needs to be done
* This is a detailed explanation
* of something that should require
* several paragraphs of information.
*/
?>
```

Is there any way I can help with this?

**Comment by dgmid** [comment]
Hi,
Sorry for the late reply.

I have thought of this, but not sure how to handle it. I'm currently using one line of regex to scan the whole document line by line for each comment type:

    regexPatterns[key] = { pattern: '([\\/\\/][\\/\\*]|#|
    //
    #
    /* */

Given that people use various different formats of block comments I would have to do some kind of multi-line scan that could get them all (as well as what I'm already scanning for).

Maybe it's not as difficult as I think it is, but I'm no expert of regex.

If you have any ideas let me know.
